# Service Post ??
server:
  port: 8080


# RabbitMQ ?? ??
spring:
  rabbitmq:
    port: 5672
    username: guest
    password: guest

  data:
    mongodb:
      uri: ${MONGODB_URI}
      authentication-database: admin
      database: ${MONGODB_DBNAME}
rabbitmq:
  exchange.name: sample.exchange
  url.queue.name: url.queue
  url.routing.key: url.key
  summary.queue.name: summary.queue
  summary.routing.key: summary.key
