# Service Post ??
server:
  port: 8080


# RabbitMQ ?? ??
spring:

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URI}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

logging:
  level:
    sql: debug
    org.hibernate.orm.jdbc.bind: trace

rabbitmq:
  exchange.name: sample.exchange
  url.queue.name: url.queue
  url.routing.key: url.key
  summary.queue.name: summary.queue
  summary.routing.key: summary.key
