# Service Post ??
server:
  port: 8080


# RabbitMQ ?? ??
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  data:
    mongodb:
      uri: ${MONGODB_URI}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URI}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

rabbitmq:
  exchange.name: sample.exchange
  url.queue.name: url.queue
  url.routing.key: url.key
  summary.queue.name: summary.queue
  summary.routing.key: summary.key
